### ISSUE TITLE
Stelthed mobs, range

### ISSUE THREAD

**Issue by TobiasFriberg** [mangosArchives/databaseZero_Rel19#120]
Made a post about stelthed mobs not showing over at https://github.com/mangoszero/database/issues/85

Like i said there..

<i>I just tried with level 45 and its way to hard, I can only see them when i walk into them, and they are from range 40-45. I should be able to detect them a bit more easy. when in level 45. I tried level 55 and i was able to see them from longer range, not verry far, but a decent range. I think it should be raised a bit tho.</i>

It's a range problem, it's not supose to be that hard to notice the stelthed mobs, same goes for all stelthed mobs.

**Comment by danielsreichenbach** [comment]
Is there any kind of screenshot or video from life servers showing off the range you are referencing too?

Would be much easier to check how far the range should be.

**Comment by Uccello** [comment]
I looked up a few areas on this, and what i could find  was mostly comments on mobs, but generally they did not have a level ( tho its safe to assume most of these were being done at the level of the quest)

Wowhead comments about shadowmaw patnthers in Stranglethorn Vale Mention that they are stealth until youre nearly ontop of them, and suggest various ways of getting them ( Hunter trackers warlock pets, target macros ect) I refer mostly to the comments from 2006-2007 ( tho they are bc since wowhead has removed vanilla comments ) It should be fairly similar. 

http://www.wowhead.com/quest=192#comments

http://www.wowhead.com/npc=684#comments

http://www.wowhead.com/npc=5615#comments

Comments also on wastewander rogues that you need to be  on top practically 

Hope this is of some help

**Comment by danielsreichenbach** [comment]
Closing this for now, since the references found indicate that the issue of seeing these creatures only from very close range is actually wanted :smile:
