### ISSUE TITLE
should continue  fix issue #112!!

### ISSUE THREAD

**Issue by weishan1981** [mangosArchives/databaseZero_Rel19#121]
in  dbscripts_on_gossip,there is no  X. Y.Z

is the positon  '1089.601685', '-470.190247', '-106.413055' right?

**Comment by danielsreichenbach** [comment]
Issue #112 is already fixed. The gossip for Lothos Riftwaker does not need any coordinates, as the actual transport to Molten Core is trigger by an action script.

Try out:

```
SELECT *  FROM `gossip_menu_option` WHERE `menu_id` = 5750;
```

As you can see, there is a action script identifier in the result. Now we lookup the matching script for the gossip menu entry:

```
SELECT *  FROM `dbscripts_on_gossip` WHERE `id` = 5750;
```

As you can see, the script will cast spell 25139 aka. [Teleport to Molten Core DND](http://www.wowhead.com/spell=25139).

Since this is a spell, has a spell effect of 5 aka SPELL_EFFECT_TELEPORT_UNITS, we now know that the teleport coordinates can be found in our database too. Try executing

```
SELECT *  FROM `spell_target_position` WHERE `id` = 25139;
```

There you have target coordinates, and the target map.

As you can see, the gossip does not require any coordinates, and IMHO I have tested #112 and it works exactly like on official servers for both factions.
