### ISSUE TITLE
Spell 768 is bugged...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#40]
The spell "Cat Form" is bugged. You are only supposed to be able to use it outside, but I can use it anywhere. I get the message "Can only be used outside", but it still changes my druid into her cat form, even inside an inn.

Also, when going inside from the outside it is supposed to change you back to your normal form. Currently, it does not.

**Comment by Ghurok** [comment]
We're going to need some proof for this because we have a screenshot (http://puu.sh/2iNR8) from classic of a horde druid in cat form inside Hall of the Brave (the PvP room in Orgrimmar). One theory could be that the druid had just been in a battleground in cat form and when teleported back to Orgrimmar after it ended the cat form hadn't been removed from him yet. None of the other ~8000 screenshots show a druid in cat form indoors which is strange. Cat form should definitely be usable in instances (they are counted as indoors) so if you're right cat form should only not be usable inside buildings in cities, villages and those type of things I suppose.

I also don't get the "Can only be used outside" on the current version of mangoszero.

**Comment by The-Great-Sephiroth** [comment]
Not trying to be snotty, but my honest answer is to read the tooltip. Cat form is only usable outside. It is supposed to work in instances however. The thing is, I can use it in inns, shops, wherever. Again, not being short with you or snotty, but if you mouse over the tooltip in the client it should clearly state that you cannot use it indoors.

**EDIT**

My bad, the tooltip does not say it. Maybe I am mistaken. Let me double-check with my guild's main druid from classic. He will know for sure.

**Comment by The-Great-Sephiroth** [comment]
Alright, I was mistaken. It is travel form that is supposed to dispel indoors and in instances, not cat form. I was wrong, sorry for the trouble!

**Comment by The-Great-Sephiroth** [comment]
Alright, I just had my friend call back. He says all forms should dispel in inns and the like in classic. I called my mother to be sure and she said the same thing, so I now have three people that have confirmed that they remember being turned back into their humanoid form when entering inns and such.

**Comment by Ghurok** [comment]
The talent Feline Swiftness says "Increases your movement speed by 15% while outdoors in Cat Form....". In my opinion that would suggest that cat form should work indoors. Otherwise there's not really any point in mentioning "while outdoors" in the Feline Swiftness tooltip. Also if Travel Form tooltip says that it only works outdoors, wouldn't it make sense that Cat Form should say the same thing? Of course this isn't definitive proof though but I think my arguments make sense.

Found this comment from TBC (2007) on wayback machine thottbot "Fact: Cat Form does work indoors but does not get the benifit of Feline Swiftness (+30%) " http://web.archive.org/web/20070518173257/http://www.thottbot.com/s783

I can't find any place where it says that Cat Form only works outdoors.

I still think we need some better proof as to how it should work.

**Comment by The-Great-Sephiroth** [comment]
What that means is that in instances, you do not get the bonus speed. I remember being demorphed upon entering inns and shops back in the day. Unfortunately I do not have video evidence of it.

**Comment by Therilith** [comment]
How often did you enter inns and shops in bear or cat form?

**Comment by Ghurok** [comment]
And do you have any proof that "outdoors" means instances?

Like I said, I don't find any proof for Cat Form only working outdoors. I did find proof from TBC that Cat Form works indoors and I can't find any patch notes mentioning Cat Form being changed from only working outdoors to working indoors as well.

I think we need more than anecdotal evidence from years after classic.

**Comment by The-Great-Sephiroth** [comment]
All I can tell you is that in classic, which is where I played for years, druids would turn back into their normal forms when going inside. Inside does not count instances. Inside is building such as inns.

**Comment by Therilith** [comment]
"Inside is building such as inns."
What about caves outside of instances?

Also, for what it's worth, Tree of Life form could be used indoors in 2.0.1.

**Comment by The-Great-Sephiroth** [comment]
Give me a few days to chat with old guildmates and do some research. I know for a **fact** that I have had my druids on official demorph when entering buildings and such. I could have sworn it was classic, but if they made this change in TBC or Lich King, so be it. I still believe, as my guilds main druid and my mother (yes, she is retired and loved WoW until MoP came out) also believe. We may be wrong, but I find it odd that we all share memories of not being able to use our forms inside.

**Comment by The-Great-Sephiroth** [comment]
Alright, while I cannot find much information online about this, I have spoken either on the phone or in person with more than a dozen people and all of them remember not being able to use their forms in buildings. They could use them in instances, but not buildings. They all remember what I do, that walking into a building while morphed would demorph you. However, this may have been changed prior to 1.12. None of us remember what patch lifted this restriction.

**Comment by Ghurok** [comment]
Video posted in 1.12.1: http://www.youtube.com/watch?feature=player_detailpage&v=v3XXZOIXrPI#t=345s
It's showing druids in Bear Form inside of Stormwind Keep and even one in Cat Form.

It wasn't necessarily recorded on the same day it was posted though. But on the 6th of Novemember (when the video was posted on YouTube) Warsong Gulch weekend was ongoing. And in the video you can see the WSG emissaries standing behind Elfarran in the video.

Another video, but posted around 12 days before 1.12.1: http://www.youtube.com/watch?feature=player_detailpage&v=_JFAQiDZLMU#t=24s

Posted in 1.12.1: http://www.youtube.com/watch?feature=player_detailpage&v=1FEerZrDtMA#t=451s You can see a druid in Bear Form if you look closely.

Posted in 1.12.1: http://www.youtube.com/watch?feature=player_detailpage&v=_IBBm49rBwI#t=245s Druid in Cat Form

**Comment by The-Great-Sephiroth** [comment]
Well that settles it, but then what version added or removed that restriction? Was it there in the beginning and then removed prior to 1.12? We all remember this, but it is clear that it was gone before 1.12 came out. Guess it does not matter since we are not trying to work on version 1.8 or something. Thanks for solving this!
